id = "mest"
name = "Mest"
version = "0.1.0"
schema_version = 1
authors = ["Gonçalo Pontes <gpm.pontes@gmail.com>"]
description = "Zed support for the Mest language"
repository = "https://github.com/goncalompontes/mestc"

[grammars.mest]
repository = "https://github.com/goncalompontes/tree-sitter-mest"
rev = "58271367d96d83eaf21600185e368c6ac6dd6c4a"
