id = "mest"
name = "Mest"
version = "0.1.0"
schema_version = 1
authors = ["Gonçalo Pontes <gpm.pontes@gmail.com>"]
description = "Zed support for the Mest language"
repository = "https://github.com/goncalompontes/mestc"

[grammars.mest]
repository = "https://github.com/goncalompontes/tree-sitter-mest"
rev = "5f89c007ccee8b0ab5bf5429d9f23adbbd4552fd"

[language_servers.mest-lsp]
name = "Mest Language Server"
language = "Mest"
